name: CI thvote-submit-handler

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/ci-submit-handler.yml
      - .github/workflows/ci-rust.yml
      - submit-handler/**
      - pvrustlib/**

jobs:
  call-build:
    uses: ./.github/workflows/ci-rust.yml
    with:
      folder: submit-handler
      name: thvote-submit-handler
